### ISSUE TITLE
Occasional `KeyError` with JSMA depending on input

### ISSUE THREAD

**Issue by apnorton** [openai/cleverhans#121]
I was using the JSMA attack (with the `increase=False` option) on "tutorial" MNIST classifier from the TensorFlow website.  However, it *occasionally* dies when trying to remove a key that does not exist:
```
Current iteration: 5 - Current Prediction: 1
Current iteration: 10 - Current Prediction: 1
Current iteration: 15 - Current Prediction: 1
Current iteration: 20 - Current Prediction: 1
Current iteration: 25 - Current Prediction: 3
Traceback (most recent call last):
  File "mnist_test_updated.py", line 245, in <module>
    max_distortion/100, False, 0, 1)
  File "/net/af11/apn4za/AdversarialMachineLearning/fjsma/cleverhans/cleverhans/attacks_tf.py", line 246, in jsma_tf
    grads_target, grads_others, search_domain, increase)
  File "/net/af11/apn4za/AdversarialMachineLearning/fjsma/cleverhans/cleverhans/attacks_tf.py", line 124, in saliency_map
    search_domain.remove(p1)
KeyError: 0
```

[Link to offending lines.][badlines]

This occurs when there are *no* pixels that satisfy the saliency map condition of `alpha < 0` and `beta > 0` (using the terms from Papernot, et al), so then "best" is 0.  However, for MNIST, the 0 pixel is *rarely* set, so it is not in the `search_domain` set and the removal fails.

I did a temporary fix on my side by using `discard` instead of `remove`, which fails silently.  The downside of this is that the saliency map will continue to delete the `0, 0` pixels until the `max_iters` value is exceeded in the main `jsma_tf` loop; this wastes resources, but is a simple fix.  

[badlines]:https://github.com/openai/cleverhans/blob/master/cleverhans/attacks_tf.py#L124-L125

**Comment by rms5643** [comment]
Can confirm. I have experienced this myself, albeit rarely. This exception occurs in two cases: the one above where no pixels satisfy the map condition and when _one_ pixel satisfies both conditions _and_ has the highest score among all pixel pairs. The assumption with `scores_mask = ((target_sum > 0) & (other_sum < 0))` is that any pixel that is paired with a pixel that is in invalid (i.e. not in our search domain) will fail to meet the condition because pixels either increase the target sum or decrease other sums, but (typically) not both.

However, I have seen a handful of times where such a pixel does exist, and is typically paired with the 0th pixel, like above, which results in the same failure. While the problem above (no pixels satisfying the map condition) needs it's own solution, I fixed my issue by adjusting `grads_target[invalid] = very_large_negative number` and `grads_other[invalid] = very_large_positive_number` (Assuming `increase = True` obviously). The error here is that we are saying invalid pixels have a neutral score, when we need to give them a bad score so that when they're paired with exceptionally good pixels (pixels with a high score), the total score is still very low. Alternatively... we could go through the scores array and set any pair's score equal to 0 if one pixel in the pair is in our `invalid` set.

**Comment by rms5643** [comment]
Can confirm. I have experienced this myself, albeit rarely. This exception occurs in two cases: the one above where no pixels satisfy the map condition and when one pixel satisfies both conditions and has the highest score among all pixel pairs. The assumption with scores_mask = ((target_sum > 0) & (other_sum < 0)) is that any pixel that is paired with a pixel that is in invalid (i.e. not in our search domain) will fail to meet the condition because pixels either increase the target sum or decrease other sums, but (typically) not both.

However, I have seen a handful of times where such a pixel does exist, and is typically paired with the 0th pixel, like above, which results in the same failure. While the problem above (no pixels satisfying the map condition) needs it's own solution, I fixed my issue by adjusting grads_target[invalid] = very_large_negative number and grads_other[invalid] = very_large_positive_number (Assuming increase = True obviously). The error here is that we are saying invalid pixels have a neutral score, when we need to give them a bad score so that when they're paired with exceptionally good pixels (pixels with a high score), the total score is still very low. Alternatively... we could go through the scores array and set any pair's score equal to 0 if one pixel in the pair is in our invalid set.
