### ISSUE TITLE
make the saliency maps more general

### ISSUE THREAD

**Issue by npapernot** [openai/cleverhans#37]
right now the map definitions are biased towards image data (because of row x col). We should clean up the code to define them for any input vector. We can do that once the tutorial is fully merged (branch saliency is closed)

**Comment by rfeinman** [comment]
Agreed that this is important. FGSM works for any input shape, but JSMA is only for image data with shape (n_samples, 1, n_rows, n_cols). This is not very well generalized because it only works for black-and-white images. We should update to work with color images and with flat vector data. I can help.

**Comment by npapernot** [comment]
Help would be welcomed yes, feel free to start a PR related to this

**Comment by npapernot** [comment]
Solved by #74
