### ISSUE TITLE
theano tutorial is incredible slow

### ISSUE THREAD

**Issue by goodfeli** [openai/cleverhans#65]
ian@11:~/cleverhans/tutorials$ KERAS_BACKEND="theano" python mnist_tutorial_th.py 
    Using Theano backend.
    INFO: '~/.keras/keras.json' sets 'image_dim_ordering' to 'tf', temporarily setting to 'th'
    X_train shape: (60000, 1, 28, 28)
    60000 train samples
    10000 test samples
    Loaded MNIST test data.
    Defined Theano model graph.
    Starting model training using Theano.
    Defined optimizer.
    Epoch 0
        Epoch took 338.5225307941437 seconds

**Comment by goodfeli** [comment]
@mahnerak do you know what could be going on?

**Comment by mahnerak** [comment]
For me, it takes about 6 seconds per epoch. (GTX980 with cuDNN enabled)

It seems like your GPU device is not enabled for theano.
By default you can see `Using gpu device 0: GeForce GTX 980 (CNMeM is disabled, cuDNN 5005)` if you're running it on a GPU.
In order to enable GPU support, add these lines to `.theanorc` file in your home directory. 
`[global]`
`device = gpu0`

**Comment by npapernot** [comment]
This should be fixed now. Feel free to reopen if that's not the case.
